# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://jinj7.github.io
date_format: "ordinal"
title: Keep studying
subtitle: ""
description: "jinj7's blog"
keywords: linux, network, c
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: jinj7
organization: github
organization_url: https://jinj7.github.io
github_username: jinj7
location: Beijing, China
email: jinj84@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: jinj7/jinj7.github.io

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: jinj7
    repo: jinj7.github.io
    oauth:
        client_id: 4db18f701656ef6ac648
        client_secret: 939282da9df41ba1155ad1549eccc10c79ae9364
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: jinj7
    repo: jinj7.github.io
    clientID: 4db18f701656ef6ac648
    clientSecret: 939282da9df41ba1155ad1549eccc10c79ae9364
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-110226116-1
